"""User-genre affinity generator for participant solution."""

from __future__ import annotations

import sys

import numpy as np
import pandas as pd
from tqdm import tqdm

from src.platform.core.dataset import Dataset


class UserGenrePopularityGenerator:
    """Generate candidates by projecting user genre affinities to editions.

    The generator translates normalized user genre profile weights into edition
    scores through the catalog's book-to-genre links and global popularity prior.
    Smoothing keeps long-tail genres from collapsing to zeros in sparse cases.
    """

    name = "user_genre"

    def __init__(self, genre_smoothing: float = 1.0, show_progress: bool = False) -> None:
        """Store hyperparameters controlling user-genre scoring.

        Args:
            genre_smoothing: Additive prior applied to per-edition popularity.
            show_progress: Whether user-level tqdm progress should be shown.
        """
        self.genre_smoothing = genre_smoothing
        self.show_progress = show_progress

    def generate(
        self,
        dataset: Dataset,
        user_ids: np.ndarray,
        features: pd.DataFrame,
        k: int,
        seed: int,
    ) -> pd.DataFrame:
        """Emit top-k genre-driven candidates per user.

        Args:
            dataset: Runtime dataset containing catalog and book-genre links.
            user_ids: Target users that must receive candidate rows.
            features: Long feature table with user profiles and popularity.
            k: Maximum candidates per user generated by this source.
            seed: Pipeline seed (unused by current deterministic implementation).

        Returns:
            Candidate DataFrame with schema expected by platform runner.
        """
        del seed
        user_profile = features[features["feature_type"] == "user_genre_profile"][
            ["user_id", "genre_id", "value"]
        ].copy()
        if user_profile.empty:
            return pd.DataFrame(columns=["user_id", "edition_id", "score", "source"])

        edition_pop = features[features["feature_type"] == "edition_popularity_all"][
            ["edition_id", "value"]
        ].copy()
        pop_map = {
            int(row["edition_id"]): float(row["value"])
            for row in edition_pop.to_dict(orient="records")
        }

        catalog_genres = dataset.catalog_df[["edition_id", "book_id"]].merge(
            dataset.book_genres_df[["book_id", "genre_id"]],
            on="book_id",
            how="inner",
        )
        catalog_genres["pop"] = catalog_genres["edition_id"].map(pop_map).fillna(0.0)
        catalog_genres = catalog_genres.sort_values(
            ["genre_id", "pop", "edition_id"], ascending=[True, False, True]
        )

        top_per_genre = max(k * 5, 200)
        genre_to_editions: dict[int, list[tuple[int, float]]] = {}
        for genre_id, group in catalog_genres.groupby("genre_id"):
            rows = group.head(top_per_genre)
            genre_to_editions[int(genre_id)] = [
                (int(edition_id), float(pop))
                for edition_id, pop in zip(rows["edition_id"].tolist(), rows["pop"].tolist())
            ]

        user_profile = user_profile[user_profile["user_id"].isin(user_ids.tolist())]
        rows: list[dict[str, int | float | str]] = []
        grouped = user_profile.groupby("user_id")
        for user_id, group in tqdm(
            grouped,
            total=user_profile["user_id"].nunique(),
            desc=f"{self.name}_users",
            leave=False,
            dynamic_ncols=True,
            disable=not (self.show_progress and sys.stdout.isatty()),
            file=sys.stdout,
        ):
            score_by_edition: dict[int, float] = {}
            for _, profile_row in group.iterrows():
                genre_id = int(profile_row["genre_id"])
                weight = float(profile_row["value"])
                for edition_id, pop in genre_to_editions.get(genre_id, []):
                    score_by_edition[edition_id] = score_by_edition.get(edition_id, 0.0) + (
                        weight * (pop + self.genre_smoothing)
                    )
            top_items = sorted(score_by_edition.items(), key=lambda x: (-x[1], x[0]))[:k]
            for edition_id, score in top_items:
                rows.append(
                    {
                        "user_id": int(user_id),
                        "edition_id": int(edition_id),
                        "score": float(score),
                        "source": self.name,
                    }
                )
        return pd.DataFrame(rows, columns=["user_id", "edition_id", "score", "source"])

